Cool refactor B)
ddm999/hs-universe pull request #1
Opened 2021-12-13 23:01 UTC by JMcB17

2021-12-13 23:30 UTC, JMcB17 commented
_No description provided._

2021-12-13 23:54 UTC, ddm999 requested changes
problems found on inspection

2021-12-13 23:54 UTC, ddm999 commented on mod_update.py
> +from __future__ import annotations
is this needed?
kinda don't want to break 3.5, 3.6 compatibility for no benefit

2021-12-13 23:54 UTC, ddm999 commented on mod_update.py
> +def main2(args: argparse.Namespace) -> int:
bruh
`checkForUpdate()`

2021-12-13 23:54 UTC, ddm999 commented on mod_update.py
> +        log.fatal("fuck it broke. press enter to close", exc_info=error)
did you run this ooi
bc python docs say it should be `critical`, not `fatal`

2021-12-13 23:54 UTC, ddm999 commented on mod_update.py
> +        ("debug", "d", "verbose", "v"): logging.DEBUG,
just get rid of verbose if there's no log level for it

2021-12-13 23:54 UTC, ddm999 commented on mod_update.py
> +                    log.debug(f"'{file_path}' skipped, unchanged from current.")
swap this with log.info() if verbose is going

2021-12-14 00:20 UTC, JMcB17 commented on mod_update.py
> +from __future__ import annotations
3.5 and 3.6 are already past end of life [^1] so I don't think it's that unreasonable. I think this is the recommended approach [^2].

[^1]: <https://endoflife.date/python> (Strictly speaking, 3.6 passes end of life in a week)
[^2]: https://www.python.org/dev/peps/pep-0585/#id6

2021-12-14 00:21 UTC, JMcB17 commented on mod_update.py
> +        log.fatal("fuck it broke. press enter to close", exc_info=error)
I didn't run this actually I don't even know what it does! I just find random code like a ravenous and refactor it naively at random. I do not see it

2021-12-14 00:23 UTC, JMcB17 commented on mod_update.py
> +                    log.debug(f"'{file_path}' skipped, unchanged from current.")
d8a789b9953ab3a8c3dba5ce380afc8217f81355

2021-12-14 00:23 UTC, JMcB17 commented on mod_update.py
> +        ("debug", "d", "verbose", "v"): logging.DEBUG,
d8a789b9953ab3a8c3dba5ce380afc8217f81355

2021-12-14 00:23 UTC, JMcB17 commented on mod_update.py
> +        log.fatal("fuck it broke. press enter to close", exc_info=error)
d8a789b9953ab3a8c3dba5ce380afc8217f81355

2021-12-14 00:23 UTC, JMcB17 commented on mod_update.py
> +def main2(args: argparse.Namespace) -> int:
d8a789b9953ab3a8c3dba5ce380afc8217f81355

2021-12-14 00:26 UTC, ddm999 commented on mod_update.py
> +from __future__ import annotations
ah, i didn't know about something partially in [2]
thats fine then

2021-12-14 00:33 UTC, ddm999 approved these changes

2021-12-14 00:54 UTC, ddm999 requested changes
problems found from actually running the code

2021-12-14 00:54 UTC, ddm999 commented on mod_update.py
> +            file_path.parent.mkdir(parents=True, exist_ok=True)
should be `file_backup_path`
or you're ensuring the existing path ... exists

2021-12-14 00:54 UTC, ddm999 commented on mod_update.py
> +            ret = urllib.request.urlopen(BASEURL+str(file_path), context=sslcontext)
use `file_path.as_posix()` to get a valid URL out instead of `str(file_path)` which will create a bad URL on Windows

2021-12-14 00:57 UTC, ddm999 commented on mod_update.py
> +    sys.exit()
don't use `sys.exit()` because this causes mod_run.py to not work

2021-12-14 01:00 UTC, JMcB17 commented on mod_update.py
> +    sys.exit()
Oh damn. Well `exit()` shouldn't be used because it's indended purely for interactive repl shell. So I'll just remove this line entirely since it's at the end of the program anyway

2021-12-14 01:02 UTC, JMcB17 commented on mod_update.py
> +            ret = urllib.request.urlopen(BASEURL+str(file_path), context=sslcontext)
071e3a06ae5ff71f8bbbd0ea681316685e6258f9

2021-12-14 01:02 UTC, JMcB17 commented on mod_update.py
> +    sys.exit()
071e3a06ae5ff71f8bbbd0ea681316685e6258f9

2021-12-14 01:04 UTC, JMcB17 commented on mod_update.py
> +            file_path.parent.mkdir(parents=True, exist_ok=True)
3f8d520b43e0a11078860d3d5ad6e4a78d6ffdcb

2021-12-15 12:09 UTC, ddm999 approved these changes

2021-12-15 12:09 UTC, ddm999 commented
will be merged with #2

2021-12-15 12:10 UTC, merged